"use client";
import {useEffect,useState} from "react";

const dollars=(minor:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(Number(minor||0)/100);
const initial={faculty_investment_minor:"",course_price_minor:"",capacity:"",target_registrations:"",processing_fee_bps:"300",approved_direct_expenses_minor:"",faculty_share_bps:"8000",kmce_share_bps:"2000",target_return_multiple:"2"};

export default function CourseRevenuePlan({courses}:{courses:any[]}){
  const [courseCode,setCourseCode]=useState(""); const [form,setForm]=useState<any>(initial); const [data,setData]=useState<any>(null); const [notice,setNotice]=useState("");
  const moneyToMinor=(value:any)=>value===""?"":String(Math.round(Number(value)*100));
  const minorToMoney=(value:any)=>value==null?"":String(Number(value)/100);
  async function load(code:string){if(!code)return; const r=await fetch(`/api/courses/${encodeURIComponent(code)}/revenue-plan`); const d=await r.json().catch(()=>null); if(!r.ok){setNotice(d?.error||"Could not load plan");return;} setData(d); const p=d.plan; setForm({faculty_investment_minor:minorToMoney(p.faculty_investment_minor),course_price_minor:minorToMoney(p.course_price_minor),capacity:String(p.capacity||""),target_registrations:String(p.target_registrations||""),processing_fee_bps:String(p.processing_fee_bps),approved_direct_expenses_minor:minorToMoney(p.approved_direct_expenses_minor),faculty_share_bps:String(p.faculty_share_bps),kmce_share_bps:String(p.kmce_share_bps),target_return_multiple:String(p.target_return_multiple)});}
  useEffect(()=>{if(courses[0]&&!courseCode){setCourseCode(courses[0].course_code);void load(courses[0].course_code);}},[courses,courseCode]);
  function set(key:string,value:string){setForm((x:any)=>({...x,[key]:value}));}
  async function save(){if(!courseCode)return; setNotice("Saving revenue plan…"); const body={...form,faculty_investment_minor:moneyToMinor(form.faculty_investment_minor),course_price_minor:moneyToMinor(form.course_price_minor),approved_direct_expenses_minor:moneyToMinor(form.approved_direct_expenses_minor)}; const r=await fetch(`/api/courses/${encodeURIComponent(courseCode)}/revenue-plan`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}); const d=await r.json().catch(()=>null); if(!r.ok){setNotice(d?.error||"Could not save plan");return;} setData(d); setNotice("REVENUE PLAN SAVED · PLANNING ONLY, NOT A REVENUE PROMISE");}
  const e=data?.economics;
  return <section className="course-block revenue-block"><div className="course-block-head"><div><div className="eyebrow">FACULTY REVENUE PLAN</div><h2>Investment, return target & execution pipeline</h2><p className="muted">Internal planning only. Nothing here publishes a price or guarantees registrations, revenue, or return.</p></div><span className="course-block-tag">PLANNING MODEL</span></div><div className="course-toolbar"><label>Course<select value={courseCode} onChange={e=>{setCourseCode(e.target.value);void load(e.target.value);}}>{courses.map(c=><option key={c.id} value={c.course_code}>{c.working_name||c.title} · Internal ID {c.course_code}</option>)}</select></label></div><div className="revenue-input-grid"><input value={form.faculty_investment_minor} onChange={e=>set("faculty_investment_minor",e.target.value)} placeholder="Faculty investment ($)" type="number" min="0" step="0.01"/><input value={form.course_price_minor} onChange={e=>set("course_price_minor",e.target.value)} placeholder="Course price ($) — not published" type="number" min="0" step="0.01"/><input value={form.capacity} onChange={e=>set("capacity",e.target.value)} placeholder="Capacity" type="number" min="0"/><input value={form.target_registrations} onChange={e=>set("target_registrations",e.target.value)} placeholder="Target registrations" type="number" min="0"/><input value={form.approved_direct_expenses_minor} onChange={e=>set("approved_direct_expenses_minor",e.target.value)} placeholder="Approved direct expenses ($)" type="number" min="0" step="0.01"/><input value={form.target_return_multiple} onChange={e=>set("target_return_multiple",e.target.value)} placeholder="Faculty return target multiple" type="number" min="0" step="0.25"/></div><div className="course-save-row"><button className="btn primary" onClick={()=>void save()}>Save Revenue Plan</button><span>Private planning data · founder controlled</span></div>{notice&&<p><b>{notice}</b></p>}{e&&<div className="revenue-kpis"><div><small>FACULTY TARGET</small><b>{dollars(e.faculty_target_minor)}</b></div><div><small>FACULTY PROJECTION</small><b>{dollars(e.faculty_projected_minor)}</b></div><div><small>GAP TO TARGET</small><b>{dollars(e.faculty_target_gap_minor)}</b></div><div><small>BREAK-EVEN REGISTRATIONS</small><b>{e.break_even_registrations??"Set price"}</b></div></div>}<div className="execution-pipeline"><div className="eyebrow">AI EXECUTION PIPELINE</div>{(data?.plan?.pipeline||[]).map((step:any,i:number)=><div className="pipeline-step" key={i}><span className="pipeline-index">{i+1}</span><div><b>{step.stage}</b><small>{step.owner}</small></div><em>{step.status}</em></div>)}</div></section>;
}
