"use client";
import {useEffect,useState} from "react";

const laneLabels:any={DIGITAL:"1 · DIGITAL TOOLKIT",LIVE_IN_PERSON:"2 · LIVE IN-PERSON SEMINAR",LIVE_IN_OFFICE:"3 · PREMIUM IN-OFFICE TRAINING",ONLINE:"4 · LIVE ONLINE / ON-DEMAND"};
const money=(minor:any)=>minor==null?"":String(Number(minor)/100);

export default function CourseOfferLanes({courses}:{courses:any[]}){
  const [courseCode,setCourseCode]=useState("");const [offers,setOffers]=useState<any[]>([]);const [notice,setNotice]=useState("");
  async function load(code:string){if(!code)return;const r=await fetch(`/api/courses/${encodeURIComponent(code)}/offers`);const d=await r.json().catch(()=>null);if(!r.ok){setNotice(d?.error||"Could not load offer lanes");return;}setOffers((d.offers||[]).map((x:any)=>({...x,proposed_price_minor:money(x.proposed_price_minor)})));setNotice(d.seeded?"":"Draft plan: save to create these four controlled offers.");}
  useEffect(()=>{if(courses[0]&&!courseCode){setCourseCode(courses[0].course_code);void load(courses[0].course_code);}},[courses,courseCode]);
  function change(i:number,key:string,value:any){setOffers(all=>all.map((x,n)=>n===i?{...x,[key]:value}:x));}
  async function save(){const payload=offers.map(x=>({...x,proposed_price_minor:x.proposed_price_minor===""?null:Math.round(Number(x.proposed_price_minor)*100)}));setNotice("Saving three-lane plan…");const r=await fetch(`/api/courses/${encodeURIComponent(courseCode)}/offers`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({offers:payload})});const d=await r.json().catch(()=>null);if(!r.ok){setNotice(d?.error||"Could not save offer lanes");return;}setOffers(d.offers.map((x:any)=>({...x,proposed_price_minor:money(x.proposed_price_minor)})));setNotice("THREE-LANE PLAN SAVED · PRICES ARE INTERNAL UNTIL APPROVED FOR LAUNCH");}
  return <section className="course-block offer-block"><div className="course-block-head"><div><div className="eyebrow">FACULTY REVENUE MODEL</div><h2>Three revenue lanes, four controlled offers</h2><p className="muted">Digital products are non-CE by default. CE can only be attached after internal authorization and required operating controls are in place.</p></div><span className="course-block-tag">CONTROLLED OFFERS</span></div><div className="course-toolbar"><label>Course<select value={courseCode} onChange={e=>{setCourseCode(e.target.value);void load(e.target.value);}}>{courses.map(c=><option key={c.id} value={c.course_code}>{c.working_name||c.title} · Internal ID {c.course_code}</option>)}</select></label></div><div className="offer-grid">{offers.map((offer,i)=><div className="offer-card" key={offer.lane}><div className="offer-card-head"><div><div className="eyebrow">{laneLabels[offer.lane]}</div><span>{offer.ce_credit_offered?"CE REQUESTED":"NON-CE / PENDING"}</span></div><i>{String(offer.offer_status||"IDEA").replaceAll("_"," ")}</i></div><input value={offer.offer_name||""} onChange={e=>change(i,"offer_name",e.target.value)} aria-label={`${offer.lane} offer name`}/><textarea value={offer.description||""} onChange={e=>change(i,"description",e.target.value)} aria-label={`${offer.lane} description`} placeholder="Offer description"/><div className="offer-controls"><input type="number" min="0" step="0.01" placeholder="Proposed price ($)" value={offer.proposed_price_minor??""} onChange={e=>change(i,"proposed_price_minor",e.target.value)}/><select value={offer.offer_status||"IDEA"} onChange={e=>change(i,"offer_status",e.target.value)}>{["IDEA","DEVELOPMENT","REVIEW","READY_TO_LAUNCH","LIVE","PAUSED","RETIRED"].map(s=><option key={s}>{s}</option>)}</select><label><input type="checkbox" checked={Boolean(offer.ce_credit_offered)} onChange={e=>change(i,"ce_credit_offered",e.target.checked)}/> CE credit requested</label></div><input value={offer.next_action||""} onChange={e=>change(i,"next_action",e.target.value)} placeholder="Best next action" style={{marginTop:8,width:"100%"}}/></div>)}<button className="btn primary" onClick={()=>void save()} style={{marginTop:12}}>Save Revenue Model</button>{notice&&<p><b>{notice}</b></p>}</div>;
}
