"use client";
import {useEffect,useMemo,useState} from "react";
const API=process.env.NEXT_PUBLIC_API_URL||"http://localhost:8000";

export default function Home(){
 const [educators,setEducators]=useState<any[]>([]),[workspace,setWorkspace]=useState<any>(null),[selected,setSelected]=useState<any>(null),[draft,setDraft]=useState("");
 async function loadEducators(){const r=await fetch(API+"/admin/educators");const d=await r.json();setEducators(d);if(d[0])loadWorkspace(d[0].id)}
 async function loadWorkspace(id:number){const r=await fetch(API+`/admin/educators/${id}/workspace`);setWorkspace(await r.json())}
 async function openLead(id:number){const r=await fetch(API+`/admin/leads/${id}`);const d=await r.json();setSelected(d);setDraft(d.outreach?.[0]?.draft_content||"")}
 async function edit(job:any){await fetch(API+`/outreach/${job.id}/draft`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({edited_by:"Kimberly Jimenez",draft_content:draft,note:"Edited in Founder Command Center"})});await openLead(selected.lead.id)}
 async function decide(job:any,action:"approve"|"reject"){const body=action==="approve"?{approved_by:"Kimberly Jimenez"}:{rejected_by:"Kimberly Jimenez",reason:"Returned for revision from Founder Command Center"};await fetch(API+`/outreach/${job.id}/${action}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});setSelected(null);loadWorkspace(workspace.educator.id)}
 useEffect(()=>{loadEducators()},[]);
 const pending=workspace?.pending_approvals?.length||0, leads=workspace?.leads||[];
 const contacted=leads.filter((x:any)=>["CONTACTED","FOLLOW_UP","REPLIED","INTERESTED","CALL_BOOKED","OPPORTUNITY","CONVERTED"].includes(x.pipeline_stage)).length;
 const replies=leads.filter((x:any)=>["REPLIED","INTERESTED","CALL_BOOKED","OPPORTUNITY","CONVERTED"].includes(x.pipeline_stage)).length;
 return <main className="shell"><header className="header"><div><div className="eyebrow">KINGDOM MINDSET CE · FOUNDER OPERATIONS</div><h1>Command Center</h1><div className="muted">Finish → Prove → Systemize → Scale</div></div><div>{workspace?.educator?.public_name||"Loading…"}</div></header>
 <div className="grid"><aside className="sidebar"><div className="eyebrow">WORKSPACE</div>{["Overview","Educators","Courses","Leads","Campaigns","Approvals","Revenue","Agent Activity","Compliance"].map((n,i)=><div className={"nav "+(n==="Leads"?"active":"")} key={n}>{n}</div>)}<hr style={{borderColor:"var(--line)"}}/><div className="eyebrow">EDUCATORS</div>{educators.map(e=><button className="btn" style={{width:"100%",marginTop:8}} onClick={()=>loadWorkspace(e.id)} key={e.id}>{e.public_name||e.legal_name}</button>)}</aside>
 <section><div className="metrics"><div className="metric"><span className="muted">LEADS</span><b>{leads.length}</b></div><div className="metric"><span className="muted">PENDING APPROVAL</span><b>{pending}</b></div><div className="metric"><span className="muted">CONTACTED</span><b>{contacted}</b></div><div className="metric"><span className="muted">REPLIES</span><b>{replies}</b></div></div>
 <div className="panel"><div className="eyebrow">EDUCATOR PIPELINE</div><h2>{workspace?.educator?.public_name||"Educator"} · Leads</h2>{leads.map((l:any)=><div className="lead" key={l.id}><div><b>{l.practice_name}</b><div className="muted">{l.decision_maker||"Decision maker research pending"} · {l.city}, {l.state}</div></div><span>{l.assigned_agent||"—"}</span><span>Score {l.qualification_score??"—"}</span><span className="pill">{l.pipeline_stage}</span><button className="btn" onClick={()=>openLead(l.id)}>Open</button></div>)}</div></section></div>
 {selected&&<div className="drawer"><button className="btn" onClick={()=>setSelected(null)}>Close</button><div className="eyebrow" style={{marginTop:24}}>LEAD DETAIL</div><h2>{selected.lead.practice_name}</h2><p className="muted">{selected.lead.qualification_reason}</p><p><b>Evidence:</b> {selected.lead.evidence}</p>{selected.outreach?.[0]&&<><div className="eyebrow">MAVEN DRAFT · GATEKEEPER REVIEW</div><textarea value={draft} onChange={e=>setDraft(e.target.value)}/><div className="actions"><button className="btn" onClick={()=>edit(selected.outreach[0])}>Save edit</button><button className="btn primary" onClick={()=>decide(selected.outreach[0],"approve")}>Approve</button><button className="btn" onClick={()=>decide(selected.outreach[0],"reject")}>Reject</button></div></>}<div className="eyebrow" style={{marginTop:28}}>ACTIVITY</div>{selected.activity.map((a:any)=><p className="muted" key={a.id}><b>{a.actor_name}</b> · {a.action}<br/>{a.detail}</p>)}</div>}
 </main>
}